using HP_Player_Console.Infrastructure.Core.Models.Requests.Accounts;
using HP_Player_Console.Infrastructure.Core.Models.Requests.Announcements;
using HP_Player_Console.Infrastructure.Core.Models.Requests.FileUploads;
using HP_Player_Console.Infrastructure.Core.Models.Requests.Notifications;
using HP_Player_Console.Infrastructure.Core.Models.Requests.Orders;
using HP_Player_Console.Infrastructure.Core.Models.Requests.OTP;
using HP_Player_Console.Infrastructure.Core.Models.Requests.Profiles;
using HP_Player_Console.Infrastructure.Core.Models.Requests.SelfExclusion;
using HP_Player_Console.Infrastructure.Core.Models.Requests.Withdrawals;
using HP_Player_Console.Infrastructure.Core.Models.Responses.Account;
using HP_Player_Console.Infrastructure.Core.Models.Responses.FileUploads;
using HP_Player_Console.Infrastructure.Core.Models.Responses.Limits;
using HP_Player_Console.Infrastructure.Core.Models.Responses.Notifications;
using HP_Player_Console.Infrastructure.Core.Models.Responses.Orders;
using HP_Player_Console.Infrastructure.Core.Models.Responses.OTP;
using HP_Player_Console.Infrastructure.Core.Models.Responses.Profiles;
using HP_Player_Console.Infrastructure.Core.Models.Responses.SelfExclusion;
using HP_Player_Console.Infrastructure.Core.Models.Responses.Withdrawals;
using HP_Player_Console.Infrastructure.Models;
using Microsoft.AspNetCore.Http;

namespace HP_Player_Console.Infrastructure.Interfaces;

public interface ICoreApi
{
    Task<CurrentAccountResponse> AccountCurrent(CancellationToken cancellationToken);
    Task<PlayersAgentResponse> GetPlayerAgentInfo(CancellationToken cancellationToken);
    Task<FindPlayerResponse> FindPlayer(FindPlayerRequest request, CancellationToken cancellationToken);
    Task UpdateUserPassword(UpdateUserPasswordRequest request, CancellationToken cancellationToken);
    Task<ProviderAccountResponse> SetProviderAccount(CancellationToken cancellationToken);
    Task<bool> SetAccountToForVerification(ForVerificationRequest request, CancellationToken cancellationToken);
    Task<AccountBonusResponse> GetAccountBonus(AccountBonusRequest request, CancellationToken cancellationToken);
    Task<OtpResponse> GenerateOTP(string mobileNumber, CancellationToken cancellationToken);
    Task<ApiBaseResponse<object>> VerifyOTP(VerifyOtpRequest request, CancellationToken cancellationToken);
    Task<OtpDataResponse> GetPendingOtp(CancellationToken cancellationToken);
    Task<OrdersVm> GetAccountOrders(CancellationToken cancellationToken);
    Task<OrdersVm> GetAccountOrdersById(long orderId, CancellationToken cancellationToken);
    Task<OrdersVm> GetAccountOrderByGame(int gameId, CancellationToken cancellationToken);
    Task<OrderItemVm> GetAccountUnusedOrderByGame(int gameId, CancellationToken cancellationToken);
    Task<OrderItemVm> GetAccountCurrentUnusedOrder(int gameId, DateTime openSchedule, CancellationToken cancellationToken);
    Task<AddOrderResponse> AddAccountOrder(AddAccountOrderRequest request, CancellationToken cancellationToken);
    Task UseOrderItemInSchedule(UseOrderItemRequest request, CancellationToken cancellationToken);
    Task RevertOrderItem(UseOrderItemRequest request, CancellationToken cancellationToken);
    Task AdvanceScheduleOrder(AdvanceScheduleOrderItemRequest request, CancellationToken cancellationToken);
    Task<OrderItemVm> GetOrderItems(GetOrderItemsRequest request, CancellationToken cancellationToken);
    Task<OrderItemResponse> GetOrderItemById(long orderItem, CancellationToken cancellationToken);
    Task DeleteOrder(long orderId, CancellationToken cancellationToken);
    Task<object> GetWithdrawalDetail(long transactionId, CancellationToken cancellationToken);
    Task<WithdrawalVmResponse> GetCurrentAccountWithdrawals(GetCurrentAccountWithdrawalsRequest request, CancellationToken cancellationToken);
    Task<AccountWithdrawalResponse> CreateAccountWithdrawal(CreateAccountWithdrawalRequest request, CancellationToken cancellationToken);
    Task UpdateWithdrawalStatus(UpdateWithdrawalStatusRequest request, CancellationToken cancellationToken);
    Task<UserDetailsResponse> GetUserById(Guid userId, CancellationToken cancellationToken);
    Task<object> UpdateProofInfo(UpdateProofInfoRequest request, CancellationToken cancellationToken);
    Task<object> UpdatePersonalDetails(UpdatePersonalDetailsRequest request, CancellationToken cancellationToken);
    Task<object> UpdateAddress(UpdateAddressRequest request, CancellationToken cancellationToken);
    Task<object> UpdateProfession(UpdateProfessionRequest request, CancellationToken cancellationToken);
    Task<object> UpdateProfileImage(UpdateProfileImageRequest request, CancellationToken cancellationToken);
    Task<UploadFileResponse> UploadImage(IFormFile fileRequest, CancellationToken cancellationToken);
    Task<UploadFileResponse> UploadBase64Image(UploadStringImage request, CancellationToken cancellationToken);
    Task<UploadFileResponse> GetImageByName(string fileName, CancellationToken cancellationToken);
    Task PostAccountNotification(NotificationInfoRequest request, CancellationToken cancellationToken);
    Task PostAccountNotificationList(NotificationListRequest request, CancellationToken cancellationToken);
    Task PostNotificationByNameRequest(NotificationByNameRequest request, CancellationToken cancellationToken);
    Task<GetNotificationListResponse> GetSearchNotifications(NotificationSearchRequest request, CancellationToken cancellationToken);
    Task<MarkAllAsReadResponse> MarkAllReadNotification(MarkAllReadRequest request, CancellationToken cancellationToken);
    Task<NotificationVm> UpdateNotification(UpdateNotificationRequest request, CancellationToken cancellationToken);
    Task<AdminExclusionResponse> GetAccountAdminExclusion(long accountId, CancellationToken cancellationToken);
    Task<AccountAdminLimitResponse> GetAccountAdminLimitResponse(long accountId, CancellationToken cancellationToken);
    Task<SelfLimitResponse> GetSelfLimitExclusion(long accountId, CancellationToken cancellationToken);
    Task<object> GetLatestLivestream(int companyId, CancellationToken cancellationToken);
    Task<object> GetActiveAnnouncements(ActiveAnnouncementsRequest request, CancellationToken cancellationToken);
    Task<SelfExclusionVmResponse> GetActiveExlusion(long accountId, CancellationToken cancellationToken);
    Task<SelfExclusionVmResponse> CreateSelfExclusion(SelfExclusionRequest request, CancellationToken cancellationToken);
    Task<SelfExclusionVmResponse> UpdateActiveExclusion(SelfExclusionRequest request, CancellationToken cancellationToken);
}
